### ISSUE TITLE
Meshlink event loop quitting sporadically

### ISSUE THREAD

**Issue by sairoop-elear** [elear-solutions/meshlink#57]
Meshlink's event loop sporadically exits the event loop after the `pselect()` call returning failure. This was caused due to passing invalid timespec arguments (here tv_nsec being more than 999999999).

**Comment by gsliepen** [comment]
0 for `tv_sec` is fine but the issue is `tv_nsec` being more than 999999999. I think this is fixed now in commit aab092b on the meshlink/master branch.

**Comment by sairoop-elear** [comment]
Ok, I'll modify the description and test the patch.

**Comment by sairoop-elear** [comment]
Tested and merged the fix in commit f23f9a3d627d74fc92a4abdea4fdb420f922d91f on elear-solutions/develop branch
